export const projects = [
  {
    title: 'Face-detection Web app',
    description: "This is a Face-Detection App based on my learnings From The Complete web dev Bootcamp.This is my first full stack project and it is deployed in Heroku",
      image: '/images/face-detector.png',
      tags: ['PostgreSQL', 'Express', 'React', 'Node'],
    source: 'https://github.com/mujtahid3996/smart-brain',
    visit: 'https://smart-brain-mujtahid.herokuapp.com/',
    id: 0,
  },
  {
    title: 'Hand Cricket',
    description:"Hand cricket is a game which is very much popular to bangladeshi school going people, we tried to make an interactive implementation of this game as our final year project(Me and my another team member).We made two separate implementation of this game-AugmentedReality and ComputerVision based.",
    image: '/images/Ar-hand-Cricket1.png',
    tags: ['Python', 'OpenCV','Unity','C#','Kivy'],
    source: 'https://github.com/mujtahid3996/handcricket-computervisionpart',
    visit: 'https://github.com/mujtahid3996/handcricket-Augmentedreality-part',
    id: 1,
  },
  {
    title: 'UserPortal',
    description: "This is a generic user portal for anyone to use with their existing system",
      image: '/images/userportal.png',
      tags: ['React', 'Node','Express','PostgreSQL'],
    source: 'https://github.com/mujtahid3996/userportal',
    visit: 'https://github.com/mujtahid3996/userportal',
    id: 2,
  },
  {
    title: 'Data-Science BootCamp',
    description: "Data-Science,Machinelearning,Deep-learning etc are must for Students graduating from IUT. This is a Github code repository for containg my dataScience related work.Except university work I also followed A popular Bootcamp in Udemy to get a general idea about the datasciendce workflow with statistics,Data analysis,Machinelearning,Neural networks and Deep learning in the industry",
    image: '/images/datascience.png',
    tags: ['Python','Tensorflow','Hadoop'],
    source: 'https://github.com/mujtahid3996/Datascrince-bootcamp',
    visit: 'https://github.com/mujtahid3996/Datascrince-bootcamp',
    id: 3,
  },
  {
    title: 'Modern JavaScript',
    description: "I completed this bootcamp to get acquinted with advance javascript concepts.The links below contains my works and practices with this BootCamp ",
      image: '/images/javascript.jpg',
      tags: [,'Prototype-inheritance','Execution-context','Runtime environment'],
    source: 'https://github.com/mujtahid3996/modern-Javascript-bootcamp',
    visit: 'https://www.youtube.com/watch?v=KuhLGuNxF8U&list=PLHiZ4m8vCp9Nflbo9a0pZuLscG_Xc7DKq',
    id: 4,
  },
  {
    title: 'Hangmangame , NotesApp, Wheatherapp ',
    description: "Implementation of several mini projects to get acquinted with advanced javascript concepts.While developing those I got the opportunity to see advanced js concepts in action",
      image: '/images/hangman.jpg',
      tags: ['ES6','Modern javascript','Netlify'],
    source: 'https://mujtahid-hangman.netlify.app/',
    visit: 'https://github.com/mujtahid3996/hangman-game',
    id: 5,
  },
  {
    title: 'Sociality:My first intiative to develop a social media of my own',
    description: "This is a full-stack, fully-featured social media application being developed by me.I am doing this to brush up my coding skill with javascript",
      image: '/images/socialmedia.png',
      tags: ["React-Redux "," Firebase "," Node ",'Matarial-UI'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 6,
  },
  {
    title: 'Data Structures and Algorithms',
    description: "This Github repository contains solved problems in Leetcode and CodeForces",
      image: '/images/ds.jpg',
      tags: ['Data-Structures','Algorithms','Dynamic-programming'],
    source: 'https://github.com/mujtahid3996/codeforces',
    visit: 'https://leetcode.com/mujtahid3996/',
    id: 7,
  },
  
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey as a student of CSE in IUT', },
  { year: 2018, text: 'worked with data structures and algorithms,solved nearly 200 problems in codeforces', },
  { year: 2019, text: 'started in web development world with Node.js,React.js and Cloud deployment' },
  { year: 2020, text: 'Started with data science world as data science was a must in university-completed a Bootcamp', },
  { year: 2021, text: 'Now again staring with web development as i have interest to take this as full time career', },
];